const TRANSLATION = {
    "en-US": {
        /* Common Actions & Labels */
        "all": "All",
        "add": "Add",
        "edit": "Edit",
        "save": "Save",
        "load": "Load",
        "cut": "Cut",
        "copy": "Copy",
        "paste": "Paste",
        "clipboard": "Clipboard",
        "file": "File",
        "fetch": "Fetch (API)",
        "parse": "Parse",
        "delete": "Delete",
        "export": "Export",
        "import": "Import",
        "select": "Select",
        "cancel": "Cancel",
        "close": "Close",
        "search": "Search",
        "sort": "Sort",
        "sorts": "Sorts",
        "filter": "Filter",
        "filters": "Filters",
        "confirm": "Yes, Proceed",
        "process": "Process",
        "confirm_delete": "Are you sure you want to delete this record?",
        "confirm_delete_bulk": "Are you sure you want to delete the selected records?",
        "layout_view": "Layout View",
        "empty": "Empty",
        "no_records": "No records found.",
        "donate": "Donate",
        "about": "About",
        "help": "Help",
        "support": "Support",
        "help_support": "Help & Support",
        "report": "Report",
        "print": "Print",

        /* Navigation */
        "business": "Business",
        "branch": "Branch",
        "branches": "Branches",
        "warehouse": "Warehouse",
        "product": "Product",
        "products": "Products",
        "nav.products": "Product List",
        "payment": "Payment",
        "payments": "Payments",
        "nav.payments": "Payments & Tax",
        "pricing": "Pricing",
        "nav.pricing": "Set Pricing",
        "nav.promos": "Promotions & Discounts",
        "customer": "Customer",
        "customers": "Customers",
        "employee": "Employee",
        "employees": "Employees",
        "orders": "Orders",
        "transaction": "Transaction",
        "transactions": "Transactions",
        "access_rights": "Access Control",
        "settings": "Settings",
        "general": "General",
        "nav.admin": "Admin Panel",
        "common.pos": "Point of Sale",

        /* POS & Cart */
        "cart.proceed_payment": "Proceed Payment",
        "cart.confirm_payment": "Confirm Payment",
        "cart.new_order": "New Order",
        "cart.default_customer": "General Customer",
        "cart.customer_placeholder": "Search name or member ID...",
        "cart.subtotal": "Subtotal",
        "cart.tax": "Tax",
        "cart.payment": "Payment Method",
        "cart.total": "Total Amount",
        "cart.print": "Print Receipt",
        "cart.confirm_payment_prompt": "Confirm payment for this order?",
        "cart.items_summary": "{{count}} Items • {{total}}",

        /* Payment Methods */
        "payment.pay_title": "{{method}} Payment",
        "payment.cash": "Cash",
        "payment.debit": "Debit / EDC",
        "payment.qris": "QRIS",

        /* Catalog */
        "catalog.search_placeholder": "Type product name, SKU, or scan barcode...",
        "catalog.all_categories": "All",

        /* Transactions */
        "transaction.bill_list": "Transaction List",
        "transaction.new": "New Sale",
        "transaction.new_desc": "Start a fresh order",
        "transaction.paid": "Paid",
        "transaction.unpaid": "Unpaid",
        "transaction.search_bar": "Search receipt / customer...",
        "transaction.summary": "Sales Summary",
        "transaction.transaction_count": "Total Orders",
        "transaction.total_tax": "Total Tax Collected",
        "transaction.total_amount": "Total Revenue",
        "transaction.items_sold": "Sold {{qty}} items",

        /* Data & Grid Control */
        "data.search_by": "Search By",
        "data.sort_by": "Sort By",
        "data.columns": "Columns",
        "data.dx_mode": "Developer Mode",
        "data.filter": "Filter",
        "data.type_date": "Date",
        "data.type_number": "Numeric",
        "data.type_basic": "General",
        "data.import_mode": "Import Mode",
        "data.search_column": "Search Column",
        "data.search_and_filters": "Search & Filters",
        "data.select_column_placeholder": "Select column...",
        "data.search_placeholder": "Search here...",
        "data.min_placeholder": "Min",
        "data.max_placeholder": "Max",
        "data.label_placeholder": "Rename Label",
        "data.sort": "Sorting",
        "data.asc": "A-Z / Lowest",
        "data.desc": "Z-A / Highest",
        "data.hide_all": "Hide All",
        "data.show_all": "Show All",
        "data.add_filter": "+ Add Filter",
        "data.add_sort": "+ Add Sorting",
        "data.visible_counter": "Showing {{visible}} of {{total}}",
        "data.format_text": "Text",
        "data.format_date": "Date",
        "data.format_number": "Number",
        "data.format_currency": "Currency",
        "data.upsert": "Upsert (Update & Insert)",
        "data.append": "Append (Add All)",
        "data.update": "Update Existing Only",
        "data.replace": "Replace All",
        "data.merge_fields": "Merge Non-Null Fields",
        "data.skip_map": "-- Skip / Do Not Map --",
        "data.form.title.create": "Insert Data",
        "data.form.title.update": "Update Data",
        "data.form.title.update_bulk": "Bulk Update",
        "data.tooltip_move_up": "Move up",
        "data.tooltip_move_down": "Move down",
        "data.tooltip_format": "Change column format",
        "data.tooltip_drag": "Drag to reorder",

        /* Form Blueprint Defaults */
        "forms.settings.title.general": "General Settings",
        "forms.settings.title.app_pos": "POS Settings",
        "forms.payment.title.default": "Payments & Tax",
        "forms.user.title.signIn": "Sign In",
        "forms.user.title.signUp": "Sign Up",
        "forms.user.title.changeProfile": "Profile",
        "forms.user.title.changeEmail": "Change Email",
        "forms.user.title.changePassword": "Change Password",
        "forms.business.title.create": "Add Business",
        "forms.business.title.update": "Update Business",
        "forms.branch.title.create": "Add Branch",
        "forms.branch.title.update": "Update Branch",
        "forms.warehouse.title.create": "Add Warehouse",
        "forms.warehouse.title.update": "Update Warehouse",
        "forms.employee.title.create": "Add Employee",
        "forms.employee.title.update": "Update Employee",
        "forms.customer.title.create": "Add Customer",
        "forms.customer.title.update": "Update Customer",
        "forms.product.title.create": "Add Product",
        "forms.product.title.update": "Update Product",
        "forms.login.label": "Login",
        "forms.login.placeholder": "Email or Username",
        "forms.password.label": "Password",
        "forms.password.placeholder": "Password",
        "forms.oldpassword.label": "Old Password",
        "forms.oldpassword.placeholder": "Current Password",
        "forms.newpassword.label": "New Password",
        "forms.newpassword.placeholder": "New Password",
        "forms.confirmpassword.label": "Confirm Password",
        "forms.confirmpassword.placeholder": "Confirm New Password",
        "forms.email.label": "Email",
        "forms.email.placeholder": "Email Address",
        "forms.email_login.label": "Account Email",
        "forms.email_login.placeholder": "Account Email Address",
        "forms.username.label": "Username",
        "forms.username.placeholder": "Username",
        "forms.slug.label": "Slug",
        "forms.slug.placeholder": "URL Slug",
        "forms.name.label": "Name",
        "forms.name.placeholder": "Name",
        "forms.phone.label": "Phone Number",
        "forms.phone.placeholder": "Handphone Number",
        "forms.address.label": "Address",
        "forms.address.placeholder": "Address",
        "forms.photo.label": "Image URL",
        "forms.photo.placeholder": "Image URL",
        "forms.imgFile.label": "Image",
        "forms.imgFile.placeholder": "Image File",
        "forms.imgUrl.label": "Image URL",
        "forms.imgUrl.placeholder": "Image URL",
        "forms.sku.label": "SKU",
        "forms.sku.placeholder": "SKU",
        "forms.uid.label": "Unique Code",
        "forms.uid.placeholder": "Unique Code",
        "forms.barcode.label": "Barcode",
        "forms.barcode.placeholder": "Barcode",
        "forms.price.label": "Price",
        "forms.price.placeholder": "Price",
        "forms.category.label": "Category",
        "forms.category.placeholder": "Category",
        "forms.taxRate.label": "Tax Rate",
        "forms.taxRate.placeholder": "0.01 = 1% - 0.10 = 10%",
        "forms.is_cash.label": "Cash Payment",
        "forms.is_cash.placeholder": "Enable Cash",
        "forms.is_transfer.label": "Transfer Payment",
        "forms.is_transfer.placeholder": "Enable Transfer",
        "forms.is_qris.label": "QRIS Payment",
        "forms.is_qris.placeholder": "Enable QRIS",
        "forms.listTransfer.label": "Transfer Options",
        "forms.listTransfer.placeholder": "Add Transfer Label",
        "forms.qrisImg.label": "Upload QRIS",
        "forms.qrisImg.placeholder": "Select QRIS Image",
        "forms.qrisCode.label": "QRIS String",
        "forms.qrisCode.placeholder": "QRIS Raw Payload",
        "forms.qrisNmid.label": "NMID",
        "forms.qrisNmid.placeholder": "NMID",
        "forms.qrisName.label": "Merchant Name",
        "forms.qrisName.placeholder": "Merchant Name",
        "forms.qrisCity.label": "Merchant City",
        "forms.qrisCity.placeholder": "Merchant City",
        "forms.isSupportMultiTransaction.label": "Multi-Transaction",
        "forms.isSupportMultiTransaction.placeholder": "Support Multi-Transaction (Open-bill)",
        "forms.enableGeolocation.label": "Geolocation",
        "forms.enableGeolocation.placeholder": "Enable Geolocation",
        "forms.has_account.label": "Create Account?",
        "forms.has_account.placeholder": "Create Account?",
        "forms.user_id.label": "User ID",
        "forms.business_id.label": "Business ID",
        "forms.branch_id.label": "Branch",
        "forms.warehouse_id.label": "Warehouse",
        "forms.hue.label": "Theme Color",
        "forms.locale.label": "Language",
        "forms.currencyStyle.label": "Currency Format",
        "forms.dateStyle.label": "Date Format",
        "forms.timeStyle.label": "Time Format",
        "forms.status.label": "Status",
        "forms.status.options.true": "Active",
        "forms.status.options.false": "Inactive",
        "forms.error.required": "This field is required"
    },
    "id-ID": {
        /* Common Actions & Labels */
        "all": "Semua",
        "add": "Tambah",
        "edit": "Sunting",
        "save": "Simpan",
        "load": "Muat",
        "cut": "Potong",
        "copy": "Salin",
        "paste": "Tempel",
        "clipboard": "Papan Klip",
        "file": "Berkas",
        "fetch": "Ambil (API)",
        "parse": "Proses",
        "delete": "Hapus",
        "export": "Ekspor",
        "import": "Impor",
        "select": "Pilih",
        "cancel": "Batal",
        "close": "Tutup",
        "search": "Cari",
        "sort": "Urutkan",
        "sorts": "Urutan",
        "filter": "Filter",
        "filters": "Filter",
        "confirm": "Ya, Lanjutkan",
        "process": "Proses",
        "confirm_delete": "Apakah Anda yakin ingin menghapus data ini?",
        "confirm_delete_bulk": "Apakah Anda yakin ingin menghapus data yang dipilih?",
        "layout_view": "Tampilan Layout",
        "empty": "Keranjang Masih Kosong",
        "no_records": "Belum Ada Data.",
        "donate": "Donasi",
        "about": "Tentang Aplikasi",
        "help": "Bantuan",
        "support": "Dukungan",
        "help_support": "Bantuan & Hubungi",
        "report": "Laporan",
        "print": "Cetak",

        /* Navigation */
        "business": "Bisnis",
        "branch": "Cabang",
        "branches": "Daftar Cabang",
        "warehouse": "Gudang",
        "product": "Produk",
        "products": "Produk",
        "nav.products": "Daftar Produk",
        "payment": "Pembayaran",
        "payments": "Pembayaran",
        "nav.payments": "Pembayaran & Pajak",
        "pricing": "Penetapan Harga",
        "nav.pricing": "Atur Harga",
        "nav.promos": "Promo & Diskon",
        "customer": "Pelanggan",
        "customers": "Pelanggan",
        "employee": "Pegawai",
        "employees": "Pegawai",
        "orders": "Pesanan",
        "transaction": "Transaksi",
        "transactions": "Transaksi",
        "access_rights": "Hak Akses",
        "settings": "Pengaturan",
        "general": "Umum",
        "nav.admin": "Panel Admin",
        "common.pos": "Kasir (POS)",

        /* POS & Cart */
        "cart.proceed_payment": "Proses Pembayaran",
        "cart.confirm_payment": "Bayar Sekarang",
        "cart.new_order": "Pesanan Baru",
        "cart.default_customer": "Pelanggan Umum",
        "cart.customer_placeholder": "Cari nama atau nomor member...",
        "cart.subtotal": "Subtotal",
        "cart.tax": "Pajak",
        "cart.payment": "Metode Pembayaran",
        "cart.total": "Total Bayar",
        "cart.print": "Cetak Struk",
        "cart.confirm_payment_prompt": "Konfirmasi pembayaran transaksi ini?",
        "cart.items_summary": "{{count}} Item • {{total}}",

        /* Payment Methods */
        "payment.pay_title": "Pembayaran {{method}}",
        "payment.cash": "Tunai",
        "payment.debit": "Debit / EDC",
        "payment.qris": "QRIS",

        /* Catalog */
        "catalog.search_placeholder": "Ketik nama, SKU, atau scan barcode...",
        "catalog.all_categories": "Semua",

        /* Transactions */
        "transaction.bill_list": "Daftar Transaksi",
        "transaction.new": "Transaksi Baru",
        "transaction.new_desc": "Mulai pesanan baru",
        "transaction.paid": "Lunas",
        "transaction.unpaid": "Belum Bayar",
        "transaction.search_bar": "Cari struk / pelanggan...",
        "transaction.summary": "Ringkasan Penjualan",
        "transaction.transaction_count": "Total Transaksi",
        "transaction.total_tax": "Total Pajak",
        "transaction.total_amount": "Total Pendapatan",
        "transaction.items_sold": "Terjual {{qty}} item",

        /* Data & Grid Control */
        "data.search_by": "Pencarian",
        "data.sort_by": "Urutkan",
        "data.columns": "Kelola Kolom",
        "data.dx_mode": "Mode Developer",
        "data.filter": "Filter",
        "data.type_date": "Tanggal",
        "data.type_number": "Angka",
        "data.type_basic": "Umum",
        "data.import_mode": "Mode Impor",
        "data.search_column": "Cari Kolom",
        "data.search_and_filters": "Cari & Filter",
        "data.select_column_placeholder": "Pilih Kolom...",
        "data.search_placeholder": "Cari di sini...",
        "data.min_placeholder": "Min",
        "data.max_placeholder": "Maks",
        "data.label_placeholder": "Nama Label",
        "data.sort": "Urutan",
        "data.asc": "A-Z / Terkecil",
        "data.desc": "Z-A / Terbesar",
        "data.hide_all": "Sembunyikan Semua",
        "data.show_all": "Tampilkan Semua",
        "data.add_filter": "+ Tambah Filter",
        "data.add_sort": "+ Tambah Urutan",
        "data.visible_counter": "Tampil: {{visible}} dari {{total}} kolom",
        "data.format_text": "Teks",
        "data.format_date": "Tanggal",
        "data.format_number": "Angka",
        "data.format_currency": "Mata Uang",
        "data.upsert": "Perbarui & Tambah (Upsert)",
        "data.append": "Tambah Semua (Append)",
        "data.update": "Hanya Perbarui Data Lama",
        "data.replace": "Timpa Semua Data",
        "data.merge_fields": "Gabungkan Bidang Non-Kosong",
        "data.skip_map": "-- Lewati / Jangan Petakan --",
        "data.form.title.create": "Tambah Data",
        "data.form.title.update": "Ubah Data",
        "data.form.title.update_bulk": "Ubah Sekaligus",
        "data.tooltip_move_up": "Geser ke atas",
        "data.tooltip_move_down": "Geser ke bawah",
        "data.tooltip_format": "Format tampilan kolom",
        "data.tooltip_drag": "Tarik untuk memindahkan",

        /* Form Blueprint Defaults */
        "forms.settings.title.general": "Pengaturan Umum",
        "forms.settings.title.app_pos": "Pengaturan Kasir",
        "forms.payment.title.default": "Pembayaran & Pajak",
        "forms.user.title.signIn": "Masuk",
        "forms.user.title.signUp": "Daftar",
        "forms.user.title.changeProfile": "Profil",
        "forms.user.title.changeEmail": "Ubah Email",
        "forms.user.title.changePassword": "Ubah Kata Sandi",
        "forms.business.title.create": "Tambah Bisnis",
        "forms.business.title.update": "Ubah Bisnis",
        "forms.branch.title.create": "Tambah Cabang",
        "forms.branch.title.update": "Ubah Cabang",
        "forms.warehouse.title.create": "Tambah Gudang",
        "forms.warehouse.title.update": "Ubah Gudang",
        "forms.employee.title.create": "Tambah Pegawai",
        "forms.employee.title.update": "Ubah Pegawai",
        "forms.customer.title.create": "Tambah Pelanggan",
        "forms.customer.title.update": "Ubah Pelanggan",
        "forms.product.title.create": "Tambah Produk",
        "forms.product.title.update": "Ubah Produk",
        "forms.login.label": "Login",
        "forms.login.placeholder": "Email atau nama pengguna",
        "forms.password.label": "Kata Sandi",
        "forms.password.placeholder": "Kata Sandi",
        "forms.oldpassword.label": "Kata Sandi Lama",
        "forms.oldpassword.placeholder": "Kata Sandi Saat Ini",
        "forms.newpassword.label": "Kata Sandi Baru",
        "forms.newpassword.placeholder": "Kata Sandi Baru",
        "forms.confirmpassword.label": "Konfirmasi Kata Sandi",
        "forms.confirmpassword.placeholder": "Konfirmasi Kata Sandi Baru",
        "forms.email.label": "Email",
        "forms.email.placeholder": "Alamat Email",
        "forms.email_login.label": "Email Akun",
        "forms.email_login.placeholder": "Alamat Email Akun",
        "forms.username.label": "Nama Pengguna",
        "forms.username.placeholder": "Nama Pengguna",
        "forms.slug.label": "Slug URL",
        "forms.slug.placeholder": "Slug URL",
        "forms.name.label": "Nama",
        "forms.name.placeholder": "Nama Lengkap",
        "forms.phone.label": "Nomor Telepon",
        "forms.phone.placeholder": "Nomor Handphone",
        "forms.address.label": "Alamat",
        "forms.address.placeholder": "Alamat Lengkap",
        "forms.photo.label": "URL Gambar",
        "forms.photo.placeholder": "URL Gambar",
        "forms.imgFile.label": "Berkas Gambar",
        "forms.imgFile.placeholder": "Pilih Gambar",
        "forms.imgUrl.label": "URL Gambar",
        "forms.imgUrl.placeholder": "Masukkan URL Gambar",
        "forms.sku.label": "SKU",
        "forms.sku.placeholder": "Kode SKU",
        "forms.uid.label": "Kode Unik",
        "forms.uid.placeholder": "Kode Unik",
        "forms.barcode.label": "Barcode",
        "forms.barcode.placeholder": "Kode Barcode",
        "forms.price.label": "Harga",
        "forms.price.placeholder": "Harga Produk",
        "forms.category.label": "Kategori",
        "forms.category.placeholder": "Pilih atau Buat Kategori",
        "forms.taxRate.label": "Tarif Pajak",
        "forms.taxRate.placeholder": "0.01 = 1% - 0.10 = 10%",
        "forms.is_cash.label": "Pembayaran Tunai",
        "forms.is_cash.placeholder": "Aktifkan Tunai",
        "forms.is_transfer.label": "Pembayaran Transfer",
        "forms.is_transfer.placeholder": "Aktifkan Transfer",
        "forms.is_qris.label": "Pembayaran QRIS",
        "forms.is_qris.placeholder": "Aktifkan QRIS",
        "forms.listTransfer.label": "Opsi Transfer Bank",
        "forms.listTransfer.placeholder": "Tambah Label Transfer",
        "forms.qrisImg.label": "Unggah QRIS",
        "forms.qrisImg.placeholder": "Pilih Gambar QRIS",
        "forms.qrisCode.label": "String QRIS",
        "forms.qrisCode.placeholder": "String QRIS Payload",
        "forms.qrisNmid.label": "NMID",
        "forms.qrisNmid.placeholder": "NMID Merchant",
        "forms.qrisName.label": "Nama Merchant",
        "forms.qrisName.placeholder": "Nama Merchant",
        "forms.qrisCity.label": "Kota Merchant",
        "forms.qrisCity.placeholder": "Kota Merchant",
        "forms.isSupportMultiTransaction.label": "Multi Transaksi",
        "forms.isSupportMultiTransaction.placeholder": "Dukungan Multi Transaksi (Open-bill)",
        "forms.enableGeolocation.label": "Geolokasi",
        "forms.enableGeolocation.placeholder": "Aktifkan Lokasi",
        "forms.has_account.label": "Buat Akun?",
        "forms.has_account.placeholder": "Buat Akun?",
        "forms.user_id.label": "ID Pengguna",
        "forms.business_id.label": "ID Bisnis",
        "forms.branch_id.label": "Cabang",
        "forms.warehouse_id.label": "Gudang",
        "forms.hue.label": "Warna Tema",
        "forms.locale.label": "Bahasa",
        "forms.currencyStyle.label": "Format Mata Uang",
        "forms.dateStyle.label": "Format Tanggal",
        "forms.timeStyle.label": "Format Waktu",
        "forms.status.label": "Status",
        "forms.status.options.true": "Aktif",
        "forms.status.options.false": "Nonaktif",
        "forms.error.required": "Bagian ini wajib diisi"
    },
    "ms-MY": {
        /* Common Actions & Labels */
        "all": "Semua",
        "add": "Tambah",
        "edit": "Sunting",
        "save": "Simpan",
        "load": "Muat",
        "cut": "Potong",
        "copy": "Salin",
        "paste": "Tampal",
        "clipboard": "Papan Klip",
        "file": "Fail",
        "fetch": "Ambil (API)",
        "parse": "Proses",
        "delete": "Padam",
        "export": "Eksport",
        "import": "Import",
        "select": "Pilih",
        "cancel": "Batal",
        "close": "Tutup",
        "search": "Cari",
        "sort": "Susun",
        "sorts": "Susunan",
        "filter": "Tapis",
        "filters": "Penapis",
        "confirm": "Ya, Teruskan",
        "process": "Proses",
        "confirm_delete": "Adakah anda pasti mahu memadam rekod ini?",
        "confirm_delete_bulk": "Adakah anda pasti mahu memadam rekod terpilih?",
        "layout_view": "Paparan Susun Atur",
        "empty": "Troli Masih Kosong",
        "no_records": "Tiada Rekod Dijumpai.",
        "donate": "Sumbang",
        "about": "Perihal Aplikasi",
        "help": "Bantuan",
        "support": "Sokongan",
        "help_support": "Bantuan & Sokongan",
        "report": "Laporan",
        "print": "Cetak",

        /* Navigation */
        "business": "Perniagaan",
        "branch": "Cawangan",
        "branches": "Senarai Cawangan",
        "warehouse": "Gudang",
        "product": "Produk",
        "products": "Produk",
        "nav.products": "Senarai Produk",
        "payment": "Pembayaran",
        "payments": "Pembayaran",
        "nav.payments": "Pembayaran & Cukai",
        "pricing": "Penetapan Harga",
        "nav.pricing": "Tetapkan Harga",
        "nav.promos": "Promo & Diskaun",
        "customer": "Pelanggan",
        "customers": "Pelanggan",
        "employee": "Pekerja",
        "employees": "Pekerja",
        "orders": "Pesanan",
        "transaction": "Transaksi",
        "transactions": "Transaksi",
        "access_rights": "Hak Akses",
        "settings": "Tetapan",
        "general": "Umum",
        "nav.admin": "Panel Admin",
        "common.pos": "Jualan (POS)",

        /* POS & Cart */
        "cart.proceed_payment": "Proses Pembayaran",
        "cart.confirm_payment": "Bayar Sekarang",
        "cart.new_order": "Pesanan Baru",
        "cart.default_customer": "Pelanggan Umum",
        "cart.customer_placeholder": "Cari nama atau ID ahli...",
        "cart.subtotal": "Subjumlah",
        "cart.tax": "Cukai",
        "cart.payment": "Kaedah Bayaran",
        "cart.total": "Jumlah Bayar",
        "cart.print": "Cetak Resit",
        "cart.confirm_payment_prompt": "Sahkan pembayaran pesanan ini?",
        "cart.items_summary": "{{count}} Item • {{total}}",

        /* Payment Methods */
        "payment.pay_title": "Bayaran {{method}}",
        "payment.cash": "Tunai",
        "payment.debit": "Debit / EDC",
        "payment.qris": "QRIS",

        /* Catalog */
        "catalog.search_placeholder": "Taip nama, SKU, atau imbas barkod...",
        "catalog.all_categories": "Semua",

        /* Transactions */
        "transaction.bill_list": "Sejarah Transaksi",
        "transaction.new": "Jualan Baru",
        "transaction.new_desc": "Mula pesanan baru",
        "transaction.paid": "Selesai",
        "transaction.unpaid": "Belum Bayar",
        "transaction.search_bar": "Cari resit / pelanggan...",
        "transaction.summary": "Ringkasan Jualan",
        "transaction.transaction_count": "Jumlah Pesanan",
        "transaction.total_tax": "Jumlah Cukai",
        "transaction.total_amount": "Jumlah Hasil",
        "transaction.items_sold": "Terjual {{qty}} item",

        /* Data & Grid Control */
        "data.search_by": "Carian",
        "data.sort_by": "Susun",
        "data.columns": "Urus Lajur",
        "data.dx_mode": "Mod Pembangun",
        "data.filter": "Tapis",
        "data.type_date": "Tarikh",
        "data.type_number": "Nombor",
        "data.type_basic": "Umum",
        "data.import_mode": "Mod Import",
        "data.search_column": "Cari Lajur",
        "data.search_and_filters": "Cari & Penapis",
        "data.select_column_placeholder": "Pilih Lajur...",
        "data.search_placeholder": "Cari di sini...",
        "data.min_placeholder": "Min",
        "data.max_placeholder": "Maks",
        "data.label_placeholder": "Nama Label",
        "data.sort": "Susunan",
        "data.asc": "A-Z / Terendah",
        "data.desc": "Z-A / Tertinggi",
        "data.hide_all": "Sembunyi Semua",
        "data.show_all": "Papar Semua",
        "data.add_filter": "+ Tambah Penapis",
        "data.add_sort": "+ Tambah Susunan",
        "data.visible_counter": "Paparan: {{visible}} dari {{total}} lajur",
        "data.format_text": "Teks",
        "data.format_date": "Tarikh",
        "data.format_number": "Nombor",
        "data.format_currency": "Mata Wang",
        "data.upsert": "Kemas Kini & Tambah (Upsert)",
        "data.append": "Tambah Semua (Append)",
        "data.update": "Kemas Kini Sedia Ada",
        "data.replace": "Ganti Semua",
        "data.merge_fields": "Gabung Medan Bukan Kosong",
        "data.skip_map": "-- Abai / Jangan Peta --",
        "data.form.title.create": "Tambah Data",
        "data.form.title.update": "Kemas Kini Data",
        "data.form.title.update_bulk": "Kemas Kini Pukal",
        "data.tooltip_move_up": "Alih ke atas",
        "data.tooltip_move_down": "Alih ke bawah",
        "data.tooltip_format": "Format paparan lajur",
        "data.tooltip_drag": "Tarik untuk alih",

        /* Form Blueprint Defaults */
        "forms.settings.title.general": "Tetapan Umum",
        "forms.settings.title.app_pos": "Tetapan POS",
        "forms.payment.title.default": "Pembayaran & Cukai",
        "forms.user.title.signIn": "Log Masuk",
        "forms.user.title.signUp": "Daftar",
        "forms.user.title.changeProfile": "Profil",
        "forms.user.title.changeEmail": "Tukar E-mel",
        "forms.user.title.changePassword": "Tukar Kata Laluan",
        "forms.business.title.create": "Tambah Perniagaan",
        "forms.business.title.update": "Kemas Kini Perniagaan",
        "forms.branch.title.create": "Tambah Cawangan",
        "forms.branch.title.update": "Kemas Kini Cawangan",
        "forms.warehouse.title.create": "Tambah Gudang",
        "forms.warehouse.title.update": "Kemas Kini Gudang",
        "forms.employee.title.create": "Tambah Pekerja",
        "forms.employee.title.update": "Kemas Kini Pekerja",
        "forms.customer.title.create": "Tambah Pelanggan",
        "forms.customer.title.update": "Kemas Kini Pelanggan",
        "forms.product.title.create": "Tambah Produk",
        "forms.product.title.update": "Kemas Kini Produk",
        "forms.login.label": "Log Masuk",
        "forms.login.placeholder": "E-mel atau Nama Pengguna",
        "forms.password.label": "Kata Laluan",
        "forms.password.placeholder": "Kata Laluan",
        "forms.oldpassword.label": "Kata Laluan Lama",
        "forms.oldpassword.placeholder": "Kata Laluan Semasa",
        "forms.newpassword.label": "Kata Laluan Baru",
        "forms.newpassword.placeholder": "Kata Laluan Baru",
        "forms.confirmpassword.label": "Sahkan Kata Laluan",
        "forms.confirmpassword.placeholder": "Sahkan Kata Laluan Baru",
        "forms.email.label": "E-mel",
        "forms.email.placeholder": "Alamat E-mel",
        "forms.email_login.label": "E-mel Akaun",
        "forms.email_login.placeholder": "Alamat E-mel Akaun",
        "forms.username.label": "Nama Pengguna",
        "forms.username.placeholder": "Nama Pengguna",
        "forms.slug.label": "Slug URL",
        "forms.slug.placeholder": "Slug URL",
        "forms.name.label": "Nama",
        "forms.name.placeholder": "Nama Penuh",
        "forms.phone.label": "Nombor Telefon",
        "forms.phone.placeholder": "Nombor Telefon Bimbit",
        "forms.address.label": "Alamat",
        "forms.address.placeholder": "Alamat Penuh",
        "forms.photo.label": "URL Gambar",
        "forms.photo.placeholder": "URL Gambar",
        "forms.imgFile.label": "Fail Gambar",
        "forms.imgFile.placeholder": "Pilih Gambar",
        "forms.imgUrl.label": "URL Gambar",
        "forms.imgUrl.placeholder": "Masukkan URL Gambar",
        "forms.sku.label": "SKU",
        "forms.sku.placeholder": "Kod SKU",
        "forms.uid.label": "Kod Unik",
        "forms.uid.placeholder": "Kod Unik",
        "forms.barcode.label": "Barkod",
        "forms.barcode.placeholder": "Kod Barkod",
        "forms.price.label": "Harga",
        "forms.price.placeholder": "Harga Produk",
        "forms.category.label": "Kategori",
        "forms.category.placeholder": "Pilih atau Cipta Kategori",
        "forms.taxRate.label": "Kadar Cukai",
        "forms.taxRate.placeholder": "0.01 = 1% - 0.10 = 10%",
        "forms.is_cash.label": "Bayaran Tunai",
        "forms.is_cash.placeholder": "Dayakan Tunai",
        "forms.is_transfer.label": "Bayaran Pindahan",
        "forms.is_transfer.placeholder": "Dayakan Pindahan",
        "forms.is_qris.label": "Bayaran QRIS",
        "forms.is_qris.placeholder": "Dayakan QRIS",
        "forms.listTransfer.label": "Pilihan Pindahan",
        "forms.listTransfer.placeholder": "Tambah Label Pindahan",
        "forms.qrisImg.label": "Muat Naik QRIS",
        "forms.qrisImg.placeholder": "Pilih Gambar QRIS",
        "forms.qrisCode.label": "Rentetan QRIS",
        "forms.qrisCode.placeholder": "Muatan QRIS Raw",
        "forms.qrisNmid.label": "NMID",
        "forms.qrisNmid.placeholder": "NMID Peniaga",
        "forms.qrisName.label": "Nama Peniaga",
        "forms.qrisName.placeholder": "Nama Peniaga",
        "forms.qrisCity.label": "Bandar Peniaga",
        "forms.qrisCity.placeholder": "Bandar Peniaga",
        "forms.isSupportMultiTransaction.label": "Pelbagai Transaksi",
        "forms.isSupportMultiTransaction.placeholder": "Sokong Pelbagai Transaksi (Open-bill)",
        "forms.enableGeolocation.label": "Geolokasi",
        "forms.enableGeolocation.placeholder": "Dayakan Lokasi",
        "forms.has_account.label": "Cipta Akaun?",
        "forms.has_account.placeholder": "Cipta Akaun?",
        "forms.user_id.label": "ID Pengguna",
        "forms.business_id.label": "ID Perniagaan",
        "forms.branch_id.label": "Cawangan",
        "forms.warehouse_id.label": "Gudang",
        "forms.hue.label": "Warna Tema",
        "forms.locale.label": "Bahasa",
        "forms.currencyStyle.label": "Format Mata Wang",
        "forms.dateStyle.label": "Format Tarikh",
        "forms.timeStyle.label": "Format Masa",
        "forms.status.label": "Status",
        "forms.status.options.true": "Aktif",
        "forms.status.options.false": "Tidak Aktif",
        "forms.error.required": "Medan ini diperlukan"
    },
    "th-TH": {
        /* Common Actions & Labels */
        "all": "ทั้งหมด",
        "add": "เพิ่ม",
        "edit": "แก้ไข",
        "save": "บันทึก",
        "load": "โหลด",
        "cut": "ตัด",
        "copy": "คัดลอก",
        "paste": "วาง",
        "clipboard": "คลิปบอร์ด",
        "file": "ไฟล์",
        "fetch": "ดึงข้อมูล",
        "parse": "แปลงข้อมูล",
        "delete": "ลบ",
        "export": "ส่งออก",
        "import": "นำเข้า",
        "select": "เลือก",
        "cancel": "ยกเลิก",
        "close": "ปิด",
        "search": "ค้นหา",
        "sort": "เรียงลำดับ",
        "sorts": "การเรียงลำดับ",
        "filter": "กรอง",
        "filters": "ตัวกรอง",
        "confirm": "ยืนยัน",
        "process": "ดำเนินการ",
        "confirm_delete": "คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้?",
        "confirm_delete_bulk": "คุณแน่ใจหรือไม่ว่าต้องการลบรายการที่เลือก?",
        "layout_view": "มุมมองเค้าโครง",
        "empty": "ตะกร้าสินค้าว่างเปล่า",
        "no_records": "ไม่พบข้อมูล",
        "donate": "บริจาค",
        "about": "เกี่ยวกับแอป",
        "help": "ช่วยเหลือ",
        "support": "สนับสนุน",
        "help_support": "ช่วยเหลือ & สนับสนุน",
        "report": "รายงาน",
        "print": "พิมพ์",

        /* Navigation */
        "business": "ธุรกิจ",
        "branch": "สาขา",
        "branches": "สาขา",
        "warehouse": "คลังสินค้า",
        "product": "สินค้า",
        "products": "สินค้า",
        "nav.products": "รายการสินค้า",
        "payment": "การชำระเงิน",
        "payments": "การชำระเงิน",
        "nav.payments": "การชำระเงิน & ภาษี",
        "pricing": "การตั้งราคา",
        "nav.pricing": "ตั้งราคา",
        "nav.promos": "โปรโมชั่น & ส่วนลด",
        "customer": "ลูกค้า",
        "customers": "ลูกค้า",
        "employee": "พนักงาน",
        "employees": "พนักงาน",
        "orders": "ออเดอร์",
        "transaction": "ธุรกรรม",
        "transactions": "ธุรกรรม",
        "access_rights": "สิทธิ์ใช้งาน",
        "settings": "ตั้งค่า",
        "general": "ทั่วไป",
        "nav.admin": "แผงควบคุม",
        "common.pos": "ระบบแคชเชียร์ (POS)",

        /* POS & Cart */
        "cart.proceed_payment": "ชำระเงิน",
        "cart.confirm_payment": "จ่ายเงิน",
        "cart.new_order": "ออเดอร์ใหม่",
        "cart.default_customer": "ลูกค้าทั่วไป",
        "cart.customer_placeholder": "ค้นหาชื่อ หรือ รหัสสมาชิก...",
        "cart.subtotal": "ย่อย",
        "cart.tax": "ภาษี",
        "cart.payment": "วิธีชำระเงิน",
        "cart.total": "ราคารวม",
        "cart.print": "พิมพ์ใบเสร็จ",
        "cart.confirm_payment_prompt": "ยืนยันการชำระเงินออเดอร์นี้หรือไม่?",
        "cart.items_summary": "{{count}} รายการ • {{total}}",

        /* Payment Methods */
        "payment.pay_title": "ชำระด้วย {{method}}",
        "payment.cash": "เงินสด",
        "payment.debit": "เดบิต / EDC",
        "payment.qris": "QRIS",

        /* Catalog */
        "catalog.search_placeholder": "พิมพ์ชื่อ, SKU หรือสแกนบาร์โค้ด...",
        "catalog.all_categories": "ทั้งหมด",

        /* Transactions */
        "transaction.bill_list": "ประวัติการขาย",
        "transaction.new": "การขายใหม่",
        "transaction.new_desc": "เริ่มออเดอร์ใหม่",
        "transaction.paid": "จ่ายแล้ว",
        "transaction.unpaid": "ค้างชำระ",
        "transaction.search_bar": "ค้นหาใบเสร็จ / ลูกค้า...",
        "transaction.summary": "สรุปยอดขาย",
        "transaction.transaction_count": "ออเดอร์ทั้งหมด",
        "transaction.total_tax": "ภาษีทั้งหมด",
        "transaction.total_amount": "รายได้ทั้งหมด",
        "transaction.items_sold": "ขายแล้ว {{qty}} ชิ้น",

        /* Data & Grid Control */
        "data.search_by": "ค้นหาด้วย",
        "data.sort_by": "เรียงตาม",
        "data.columns": "จัดการคอลัมน์",
        "data.dx_mode": "โหมดนักพัฒนา",
        "data.filter": "ตัวกรอง",
        "data.type_date": "วันที่",
        "data.type_number": "ตัวเลข",
        "data.type_basic": "ทั่วไป",
        "data.import_mode": "โหมดนำเข้า",
        "data.search_column": "ค้นหาคอลัมน์",
        "data.search_and_filters": "ค้นหา & ตัวกรอง",
        "data.select_column_placeholder": "เลือกคอลัมน์...",
        "data.search_placeholder": "ค้นหาที่นี่...",
        "data.min_placeholder": "ขั้นต่ำ",
        "data.max_placeholder": "สูงสุด",
        "data.label_placeholder": "ชื่อเลเบล",
        "data.sort": "การเรียงลำดับ",
        "data.asc": "A-Z / น้อยไปมาก",
        "data.desc": "Z-A / มากไปน้อย",
        "data.hide_all": "ซ่อนทั้งหมด",
        "data.show_all": "แสดงทั้งหมด",
        "data.add_filter": "+ เพิ่มตัวกรอง",
        "data.add_sort": "+ เพิ่มการเรียง",
        "data.visible_counter": "แสดง: {{visible}} จาก {{total}} คอลัมน์",
        "data.format_text": "ข้อความ",
        "data.format_date": "วันที่",
        "data.format_number": "ตัวเลข",
        "data.format_currency": "สกุลเงิน",
        "data.upsert": "อัปเดต & เพิ่ม (Upsert)",
        "data.append": "ต่อท้ายทั้งหมด (Append)",
        "data.update": "อัปเดตเฉพาะที่มีอยู่",
        "data.replace": "เขียนทับทั้งหมด",
        "data.merge_fields": "รวมฟิลด์ที่ไม่เป็นค่าว่าง",
        "data.skip_map": "-- ข้าม / ไม่จับคู่ --",
        "data.form.title.create": "เพิ่มข้อมูล",
        "data.form.title.update": "แก้ไขข้อมูล",
        "data.form.title.update_bulk": "แก้ไขพร้อมกัน",
        "data.tooltip_move_up": "เลื่อนขึ้น",
        "data.tooltip_move_down": "เลื่อนลง",
        "data.tooltip_format": "เปลี่ยนรูปแบบคอลัมน์",
        "data.tooltip_drag": "ลากเพื่อจัดเรียง",

        /* Form Blueprint Defaults */
        "forms.settings.title.general": "ตั้งค่าทั่วไป",
        "forms.settings.title.app_pos": "ตั้งค่าระบบแคชเชียร์",
        "forms.payment.title.default": "การชำระเงิน & ภาษี",
        "forms.user.title.signIn": "เข้าสู่ระบบ",
        "forms.user.title.signUp": "ลงทะเบียน",
        "forms.user.title.changeProfile": "โปรไฟล์",
        "forms.user.title.changeEmail": "เปลี่ยนอีเมล",
        "forms.user.title.changePassword": "เปลี่ยนรหัสผ่าน",
        "forms.business.title.create": "เพิ่มธุรกิจ",
        "forms.business.title.update": "แก้ไขธุรกิจ",
        "forms.branch.title.create": "เพิ่มสาขา",
        "forms.branch.title.update": "แก้ไขสาขา",
        "forms.warehouse.title.create": "เพิ่มคลังสินค้า",
        "forms.warehouse.title.update": "แก้ไขคลังสินค้า",
        "forms.employee.title.create": "เพิ่มพนักงาน",
        "forms.employee.title.update": "แก้ไขพนักงาน",
        "forms.customer.title.create": "เพิ่มลูกค้า",
        "forms.customer.title.update": "แก้ไขลูกค้า",
        "forms.product.title.create": "เพิ่มสินค้า",
        "forms.product.title.update": "แก้ไขสินค้า",
        "forms.login.label": "เข้าสู่ระบบ",
        "forms.login.placeholder": "อีเมล หรือ ชื่อผู้ใช้",
        "forms.password.label": "รหัสผ่าน",
        "forms.password.placeholder": "รหัสผ่าน",
        "forms.oldpassword.label": "รหัสผ่านเดิม",
        "forms.oldpassword.placeholder": "รหัสผ่านปัจจุบัน",
        "forms.newpassword.label": "รหัสผ่านใหม่",
        "forms.newpassword.placeholder": "รหัสผ่านใหม่",
        "forms.confirmpassword.label": "ยืนยันรหัสผ่าน",
        "forms.confirmpassword.placeholder": "ยืนยันรหัสผ่านใหม่",
        "forms.email.label": "อีเมล",
        "forms.email.placeholder": "ที่อยู่อีเมล",
        "forms.email_login.label": "อีเมลบัญชี",
        "forms.email_login.placeholder": "ที่อยู่อีเมลบัญชี",
        "forms.username.label": "ชื่อผู้ใช้",
        "forms.username.placeholder": "ชื่อผู้ใช้",
        "forms.slug.label": "สลัก URL",
        "forms.slug.placeholder": "สลัก URL",
        "forms.name.label": "ชื่อ",
        "forms.name.placeholder": "ชื่อเต็ม",
        "forms.phone.label": "เบอร์โทรศัพท์",
        "forms.phone.placeholder": "เบอร์โทรศัพท์มือถือ",
        "forms.address.label": "ที่อยู่",
        "forms.address.placeholder": "ที่อยู่เต็ม",
        "forms.photo.label": "URL รูปภาพ",
        "forms.photo.placeholder": "URL รูปภาพ",
        "forms.imgFile.label": "ไฟล์รูปภาพ",
        "forms.imgFile.placeholder": "เลือกรูปภาพ",
        "forms.imgUrl.label": "URL รูปภาพ",
        "forms.imgUrl.placeholder": "ใส่ URL รูปภาพ",
        "forms.sku.label": "SKU",
        "forms.sku.placeholder": "รหัส SKU",
        "forms.uid.label": "รหัสเฉพาะ",
        "forms.uid.placeholder": "รหัสเฉพาะ",
        "forms.barcode.label": "บาร์โค้ด",
        "forms.barcode.placeholder": "รหัสบาร์โค้ด",
        "forms.price.label": "ราคา",
        "forms.price.placeholder": "ราคาสินค้า",
        "forms.category.label": "หมวดหมู่",
        "forms.category.placeholder": "เลือกหรือสร้างหมวดหมู่",
        "forms.taxRate.label": "อัตราภาษี",
        "forms.taxRate.placeholder": "0.01 = 1% - 0.10 = 10%",
        "forms.is_cash.label": "ชำระเงินสด",
        "forms.is_cash.placeholder": "เปิดใช้เงินสด",
        "forms.is_transfer.label": "ชำระโอนเงิน",
        "forms.is_transfer.placeholder": "เปิดใช้โอนเงิน",
        "forms.is_qris.label": "ชำระ QRIS",
        "forms.is_qris.placeholder": "เปิดใช้ QRIS",
        "forms.listTransfer.label": "ตัวเลือกการโอน",
        "forms.listTransfer.placeholder": "เพิ่มป้ายกำกับโอนเงิน",
        "forms.qrisImg.label": "อัปโหลด QRIS",
        "forms.qrisImg.placeholder": "เลือกรูปภาพ QRIS",
        "forms.qrisCode.label": "ข้อความ QRIS",
        "forms.qrisCode.placeholder": "ข้อความ QRIS Raw Payload",
        "forms.qrisNmid.label": "NMID",
        "forms.qrisNmid.placeholder": "NMID ร้านค้า",
        "forms.qrisName.label": "ชื่อร้านค้า",
        "forms.qrisName.placeholder": "ชื่อร้านค้า",
        "forms.qrisCity.label": "เมืองร้านค้า",
        "forms.qrisCity.placeholder": "เมืองร้านค้า",
        "forms.isSupportMultiTransaction.label": "หลายธุรกรรม",
        "forms.isSupportMultiTransaction.placeholder": "รองรับหลายออเดอร์พร้อมกัน (Open-bill)",
        "forms.enableGeolocation.label": "พิกัดตำแหน่ง",
        "forms.enableGeolocation.placeholder": "เปิดใช้พิกัดตำแหน่ง",
        "forms.has_account.label": "สร้างบัญชี?",
        "forms.has_account.placeholder": "สร้างบัญชี?",
        "forms.user_id.label": "รหัสผู้ใช้",
        "forms.business_id.label": "รหัสธุรกิจ",
        "forms.branch_id.label": "สาขา",
        "forms.warehouse_id.label": "คลังสินค้า",
        "forms.hue.label": "สีธีม",
        "forms.locale.label": "ภาษา",
        "forms.currencyStyle.label": "รูปแบบสกุลเงิน",
        "forms.dateStyle.label": "รูปแบบวันที่",
        "forms.timeStyle.label": "รูปแบบเวลา",
        "forms.status.label": "สถานะ",
        "forms.status.options.true": "ใช้งาน",
        "forms.status.options.false": "ไม่ใช้งาน",
        "forms.error.required": "จำเป็นต้องกรอกข้อมูลนี้"
    },
    "hi-IN": {
        /* Common Actions & Labels */
        "all": "सभी",
        "add": "जोड़ें",
        "edit": "संपादित करें",
        "save": "सहेजें",
        "load": "लोड करें",
        "cut": "कट करें",
        "copy": "कॉपी करें",
        "paste": "पेस्ट करें",
        "clipboard": "क्लिपबोर्ड",
        "file": "फ़ाइल",
        "fetch": "प्राप्त करें (API)",
        "parse": "प्रोसेस करें",
        "delete": "हटाएं",
        "export": "निर्यात करें",
        "import": "आयात करें",
        "select": "चुनें",
        "cancel": "रद्द करें",
        "close": "बंद करें",
        "search": "खोजें",
        "sort": "क्रमबद्ध करें",
        "sorts": "क्रमबद्धता",
        "filter": "फ़िल्टर",
        "filters": "फ़िल्टर",
        "confirm": "हां, आगे बढ़ें",
        "process": "प्रोसेस करें",
        "confirm_delete": "क्या आप इस रिकॉर्ड को हटाना चाहते हैं?",
        "confirm_delete_bulk": "क्या आप चयनित रिकॉर्ड हटाना चाहते हैं?",
        "layout_view": "लेआउट देखें",
        "empty": "कार्ट खाली है",
        "no_records": "कोई रिकॉर्ड नहीं मिला।",
        "donate": "दान करें",
        "about": "ऐप के बारे में",
        "help": "सहायता",
        "support": "समर्थन",
        "help_support": "सहायता और समर्थन",
        "report": "रिपोर्ट",
        "print": "प्रिंट करें",

        /* Navigation */
        "business": "व्यवसाय",
        "branch": "शाखा",
        "branches": "शाखाएं",
        "warehouse": "गोदाम",
        "product": "उत्पाद",
        "products": "उत्पाद",
        "nav.products": "उत्पाद सूची",
        "payment": "भुगतान",
        "payments": "भुगतान",
        "nav.payments": "भुगतान और कर",
        "pricing": "मूल्य निर्धारण",
        "nav.pricing": "मूल्य सेट करें",
        "nav.promos": "प्रोमो और छूट",
        "customer": "ग्राहक",
        "customers": "ग्राहक",
        "employee": "कर्मचारी",
        "employees": "कर्मचारी",
        "orders": "ऑर्डर",
        "transaction": "लेन-देन",
        "transactions": "लेन-देन",
        "access_rights": "पहुंच अधिकार",
        "settings": "सेटिंग्स",
        "general": "सामान्य",
        "nav.admin": "एडमिन पैनल",
        "common.pos": "बिक्री बिंदु (POS)",

        /* POS & Cart */
        "cart.proceed_payment": "भुगतान प्रक्रिया",
        "cart.confirm_payment": "अभी भुगतान करें",
        "cart.new_order": "नया ऑर्डर",
        "cart.default_customer": "सामान्य ग्राहक",
        "cart.customer_placeholder": "नाम या सदस्य आईडी खोजें...",
        "cart.subtotal": "उप-योग",
        "cart.tax": "कर (Tax)",
        "cart.payment": "भुगतान का तरीका",
        "cart.total": "कुल राशि",
        "cart.print": "रसीद प्रिंट करें",
        "cart.confirm_payment_prompt": "क्या आप इस ऑर्डर के भुगतान की पुष्टि करते हैं?",
        "cart.items_summary": "{{count}} आइटम • {{total}}",

        /* Payment Methods */
        "payment.pay_title": "{{method}} भुगतान",
        "payment.cash": "नकद",
        "payment.debit": "डेबिट / EDC",
        "payment.qris": "QRIS",

        /* Catalog */
        "catalog.search_placeholder": "उत्पाद का नाम, SKU या बारकोड स्कैन करें...",
        "catalog.all_categories": "सभी",

        /* Transactions */
        "transaction.bill_list": "लेन-देन इतिहास",
        "transaction.new": "नई बिक्री",
        "transaction.new_desc": "नया ऑर्डर शुरू करें",
        "transaction.paid": "भुगतान किया गया",
        "transaction.unpaid": "बकाया",
        "transaction.search_bar": "रसीद / ग्राहक खोजें...",
        "transaction.summary": "बिक्री सारांश",
        "transaction.transaction_count": "कुल ऑर्डर",
        "transaction.total_tax": "कुल एकत्र कर",
        "transaction.total_amount": "कुल राजस्व",
        "transaction.items_sold": "{{qty}} आइटम बेचे गए",

        /* Data & Grid Control */
        "data.search_by": "द्वारा खोजें",
        "data.sort_by": "द्वारा क्रमबद्ध करें",
        "data.columns": "स्तंभ प्रबंधित करें",
        "data.dx_mode": "डेवलपर मोड",
        "data.filter": "फ़िल्टर",
        "data.type_date": "तिथि",
        "data.type_number": "संख्यात्मक",
        "data.type_basic": "सामान्य",
        "data.import_mode": "आयात मोड",
        "data.search_column": "स्तंभ खोजें",
        "data.search_and_filters": "खोज और फ़िल्टर",
        "data.select_column_placeholder": "स्तंभ चुनें...",
        "data.search_placeholder": "यहां खोजें...",
        "data.min_placeholder": "न्यूनतम",
        "data.max_placeholder": "अधिकतम",
        "data.label_placeholder": "लेबल बदलें",
        "data.sort": "क्रमबद्ध करना",
        "data.asc": "A-Z / न्यूनतम",
        "data.desc": "Z-A / अधिकतम",
        "data.hide_all": "सभी छिपाएं",
        "data.show_all": "सभी दिखाएं",
        "data.add_filter": "+ फ़िल्टर जोड़ें",
        "data.add_sort": "+ क्रमबद्धता जोड़ें",
        "data.visible_counter": "दिखा रहा है: {{visible}} / {{total}} स्तंभ",
        "data.format_text": "टेक्स्ट",
        "data.format_date": "तिथि",
        "data.format_number": "संख्या",
        "data.format_currency": "मुद्रा",
        "data.upsert": "अपडेट और जोड़ें (Upsert)",
        "data.append": "सभी जोड़ें (Append)",
        "data.update": "केवल मौजूदा अपडेट करें",
        "data.replace": "सभी बदलें",
        "data.merge_fields": "गैर-रिक्त फ़ील्ड मर्ज करें",
        "data.skip_map": "-- छोड़ें / मैप न करें --",
        "data.form.title.create": "डेटा जोड़ें",
        "data.form.title.update": "डेटा अपडेट करें",
        "data.form.title.update_bulk": "एक साथ अपडेट करें",
        "data.tooltip_move_up": "ऊपर ले जाएं",
        "data.tooltip_move_down": "नीचे ले जाएं",
        "data.tooltip_format": "स्तंभ का स्वरूप बदलें",
        "data.tooltip_drag": "पुनः व्यवस्थित करने के लिए खींचें",

        /* Form Blueprint Defaults */
        "forms.settings.title.general": "सामान्य सेटिंग्स",
        "forms.settings.title.app_pos": "POS सेटिंग्स",
        "forms.payment.title.default": "भुगतान और कर",
        "forms.user.title.signIn": "साइन इन करें",
        "forms.user.title.signUp": "साइन अप करें",
        "forms.user.title.changeProfile": "प्रोफ़ाइल",
        "forms.user.title.changeEmail": "ईमेल बदलें",
        "forms.user.title.changePassword": "पासवर्ड बदलें",
        "forms.business.title.create": "व्यवसाय जोड़ें",
        "forms.business.title.update": "व्यवसाय अपडेट करें",
        "forms.branch.title.create": "शाखा जोड़ें",
        "forms.branch.title.update": "शाखा अपडेट करें",
        "forms.warehouse.title.create": "गोदाम जोड़ें",
        "forms.warehouse.title.update": "गोदाम अपडेट करें",
        "forms.employee.title.create": "कर्मचारी जोड़ें",
        "forms.employee.title.update": "कर्मचारी अपडेट करें",
        "forms.customer.title.create": "ग्राहक जोड़ें",
        "forms.customer.title.update": "ग्राहक अपडेट करें",
        "forms.product.title.create": "उत्पाद जोड़ें",
        "forms.product.title.update": "उत्पाद अपडेट करें",
        "forms.login.label": "लॉगिन",
        "forms.login.placeholder": "ईमेल या उपयोगकर्ता नाम",
        "forms.password.label": "पासवर्ड",
        "forms.password.placeholder": "पासवर्ड",
        "forms.oldpassword.label": "पुराना पासवर्ड",
        "forms.oldpassword.placeholder": "वर्तमान पासवर्ड",
        "forms.newpassword.label": "नया पासवर्ड",
        "forms.newpassword.placeholder": "नया पासवर्ड",
        "forms.confirmpassword.label": "पासवर्ड की पुष्टि करें",
        "forms.confirmpassword.placeholder": "नए पासवर्ड की पुष्टि करें",
        "forms.email.label": "ईमेल",
        "forms.email.placeholder": "ईमेल पता",
        "forms.email_login.label": "खाता ईमेल",
        "forms.email_login.placeholder": "खाता ईमेल पता",
        "forms.username.label": "उपयोगकर्ता नाम",
        "forms.username.placeholder": "उपयोगकर्ता नाम",
        "forms.slug.label": "URL स्लग",
        "forms.slug.placeholder": "URL स्लग",
        "forms.name.label": "नाम",
        "forms.name.placeholder": "पूरा नाम",
        "forms.phone.label": "फ़ोन नंबर",
        "forms.phone.placeholder": "मोबाइल नंबर",
        "forms.address.label": "पता",
        "forms.address.placeholder": "पूरा पता",
        "forms.photo.label": "इमेज URL",
        "forms.photo.placeholder": "इमेज URL",
        "forms.imgFile.label": "इमेज फ़ाइल",
        "forms.imgFile.placeholder": "इमेज चुनें",
        "forms.imgUrl.label": "इमेज URL",
        "forms.imgUrl.placeholder": "इमेज URL दर्ज करें",
        "forms.sku.label": "SKU",
        "forms.sku.placeholder": "SKU कोड",
        "forms.uid.label": "विशिष्ट कोड",
        "forms.uid.placeholder": "विशिष्ट कोड",
        "forms.barcode.label": "बारकोड",
        "forms.barcode.placeholder": "बारकोड कोड",
        "forms.price.label": "मूल्य",
        "forms.price.placeholder": "उत्पाद का मूल्य",
        "forms.category.label": "श्रेणी",
        "forms.category.placeholder": "श्रेणी चुनें या बनाएं",
        "forms.taxRate.label": "कर दर",
        "forms.taxRate.placeholder": "0.01 = 1% - 0.10 = 10%",
        "forms.is_cash.label": "नकद भुगतान",
        "forms.is_cash.placeholder": "नकद सक्षम करें",
        "forms.is_transfer.label": "ट्रांसफर भुगतान",
        "forms.is_transfer.placeholder": "ट्रांसफर सक्षम करें",
        "forms.is_qris.label": "QRIS भुगतान",
        "forms.is_qris.placeholder": "QRIS सक्षम करें",
        "forms.listTransfer.label": "ट्रांसफर विकल्प",
        "forms.listTransfer.placeholder": "ट्रांसफर लेबल जोड़ें",
        "forms.qrisImg.label": "QRIS अपलोड करें",
        "forms.qrisImg.placeholder": "QRIS इमेज चुनें",
        "forms.qrisCode.label": "QRIS स्ट्रिंग",
        "forms.qrisCode.placeholder": "QRIS रॉ पेलोड",
        "forms.qrisNmid.label": "NMID",
        "forms.qrisNmid.placeholder": "मर्चेंट NMID",
        "forms.qrisName.label": "मर्चेंट नाम",
        "forms.qrisName.placeholder": "मर्चेंट का नाम",
        "forms.qrisCity.label": "मर्चेंट शहर",
        "forms.qrisCity.placeholder": "मर्चेंट का शहर",
        "forms.isSupportMultiTransaction.label": "मल्टी-ट्रांजैक्शन",
        "forms.isSupportMultiTransaction.placeholder": "मल्टी-ट्रांजैक्शन सक्षम करें (Open-bill)",
        "forms.enableGeolocation.label": "जियोलोकेशन",
        "forms.enableGeolocation.placeholder": "स्थान सक्षम करें",
        "forms.has_account.label": "खाता बनाएं?",
        "forms.has_account.placeholder": "खाता बनाएं?",
        "forms.user_id.label": "उपयोगकर्ता आईडी",
        "forms.business_id.label": "व्यवसाय आईडी",
        "forms.branch_id.label": "शाखा",
        "forms.warehouse_id.label": "गोदाम",
        "forms.hue.label": "थीम का रंग",
        "forms.locale.label": "भाषा",
        "forms.currencyStyle.label": "मुद्रा प्रारूप",
        "forms.dateStyle.label": "तिथि प्रारूप",
        "forms.timeStyle.label": "समय प्रारूप",
        "forms.status.label": "स्थिति",
        "forms.status.options.true": "सक्रिय",
        "forms.status.options.false": "निष्क्रिय",
        "forms.error.required": "यह जानकारी अनिवार्य है"
    }
};